### ISSUE TITLE
Checkmark appears when you back out of a game

### ISSUE THREAD

**Issue by jonathan-irvin** [jenn-codes/chemical-elements#1]
<img width="852" alt="Screen Shot 2022-08-29 at 1 15 56 PM" src="https://user-images.githubusercontent.com/2481437/187270379-a2683768-cadf-460a-98fb-6d412c0e1f95.png">

Steps to reproduce:
1. Click on Easy to start a game
2. Select the hydroden box and choose successfully
3. Click back

**Comment by jenn-codes** [comment]
Fixed this by removing all checkmarks from the page in the returned function of a useEffect hook with an empty dependency array. I believe this will be triggered whenever the component unmounts.
