### ISSUE TITLE
UseEffects need dependencies

### ISSUE THREAD

**Issue by jonathan-irvin** [jenn-codes/chemical-elements#3]
Something I noticed:
```
useEffect(() => {
        if (elementsLeft.length < 1) {
            setIsGameOver(!isGameOver);
            setStatus(`Wow! You found all the elements in ${timer} seconds.`);
            document.querySelector('.timer').textContent = `Timer: ${timer}`;
            // eslint-disable-next-line
        }}, [timer]); 
```

Try to avoid `//eslint-disable-next-line` and instead either fix the issue or adjust your eslint rules. 

`useEffect(<function>, <array of dependencies>)`

UseEffect takes a callback function and then an array of variables it monitors for changes. When those variables change, it triggers the callback. 

If you reference any of the variables in a `useEffect` make sure you include it in the array of dependencies so it's handled correctly. 

From the snippet above, I believe you need to add `elementsLeft` and `isGameOver`

**Comment by jenn-codes** [comment]
Added relevant variables in dependency arrays.
